# The host and port of the server
host:   http://dockerhost     # overriden with $HOST if set
port:   8080                  # overriden with $PORT if set

#redic conf
redisHost: tcp://dockerhost   # overriden with $REDIS_PORT_6379_TCP if set
redisPort: 6379               # overriden with $REDIS_PORT_6379_PORT if set